### ISSUE TITLE
Play & Pause function 

### ISSUE THREAD

**Issue by qlubZ** [Xitee1/multimedia-knob#1]
Hey! This is amazing. Thanks for your effort.

Everything other than short_press() works fine for me but I can't play or pause anything with encoder's button. Does it work for you? I don't know how to fix it.

**Comment by Xitee1** [comment]
For me short press (Play/Pause) works perfectly fine.

If you set debug to True, do you see a message called "short-press" in the console?

**Comment by qlubZ** [comment]
Yes, I see short-press when I click on encoder but there is no action.

**Comment by Xitee1** [comment]
On what type of PC and what operating system are you using? On my Windows PC it is working.
Have you tried plugging it in on another machine?

**Comment by qlubZ** [comment]
I've tried with a new pc and it worked. I have no clue why it did not work on my old one. Both of them are win10. Anyways, thank you.
